"""Regenerates src/pose/canonical.rs from MediaPipe's face_landmarker.task.

The .task file is a zip. Inside it, geometry_pipeline_metadata_landmarks.binarypb
holds the canonical face mesh and the weighted landmarks MediaPipe uses to fit
head pose. This script decodes that protobuf by hand so it needs no packages.

Usage: python3 scripts/gen_canonical.py path/to/face_landmarker.task > src/pose/canonical.rs
"""

import struct
import sys
import zipfile

METADATA = "geometry_pipeline_metadata_landmarks.binarypb"


def varint(b, i):
    result = shift = 0
    while True:
        c = b[i]
        i += 1
        result |= (c & 0x7F) << shift
        shift += 7
        if c < 0x80:
            return result, i


def fields(b):
    """Yields (field number, wire type, value) for each field in a message."""
    i = 0
    while i < len(b):
        key, i = varint(b, i)
        number, wire = key >> 3, key & 7
        if wire == 0:
            value, i = varint(b, i)
        elif wire == 5:
            value, i = b[i : i + 4], i + 4
        elif wire == 1:
            value, i = b[i : i + 8], i + 8
        elif wire == 2:
            n, i = varint(b, i)
            value, i = b[i : i + n], i + n
        else:
            raise ValueError(f"unsupported wire type {wire}")
        yield number, wire, value


def main():
    data = zipfile.ZipFile(sys.argv[1]).read(METADATA)

    # GeometryPipelineMetadata: canonical_mesh = 1, procrustes_landmark_basis = 2.
    mesh, basis = None, []
    for number, _, value in fields(data):
        if number == 1:
            mesh = value
        elif number == 2:
            landmark = weight = None
            for n, _, v in fields(value):
                if n == 1:
                    landmark = v
                elif n == 2:
                    weight = struct.unpack("<f", v)[0]
            basis.append((landmark, weight))

    # Mesh3d: vertex_buffer = 3, five floats per vertex (x, y, z, u, v).
    floats = []
    for number, wire, value in fields(mesh):
        if number == 3:
            if wire == 2:
                floats += struct.unpack(f"<{len(value) // 4}f", value)
            else:
                floats.append(struct.unpack("<f", value)[0])
    vertices = [floats[k * 5 : k * 5 + 3] for k in range(len(floats) // 5)]

    def f(x):
        return f"{x:.7g}" if "." in f"{x:.7g}" or "e" in f"{x:.7g}" else f"{x:.7g}.0"

    print("// Generated by scripts/gen_canonical.py from MediaPipe's")
    print("// geometry_pipeline_metadata_landmarks.binarypb inside face_landmarker.task.")
    print("// MediaPipe is Apache-2.0. Do not edit by hand.")
    print("//")
    print("// Each entry is (landmark index, Procrustes weight, canonical x, y, z). The")
    print("// canonical face is in centimeters, with x toward the face's own left, y up,")
    print("// and z pointing out of the face. These are the landmarks MediaPipe uses to")
    print("// fit head pose.")
    print()
    print(f"pub const PROCRUSTES_POINTS: [(usize, f32, [f32; 3]); {len(basis)}] = [")
    for landmark, weight in basis:
        x, y, z = vertices[landmark]
        print(f"    ({landmark}, {f(weight)}, [{f(x)}, {f(y)}, {f(z)}]),")
    print("];")


if __name__ == "__main__":
    main()
